import React, {useState, useEffect} from 'react';
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import dynamic from 'next/dynamic';

const HelloComponents = dynamic(() => import("../components/hello"), {
  loading : () => <b>Loading...</b>
});

const DynamicSSRTrue = dynamic(() => import("../components/dynamicSSR"), {
  ssr : true,
  loading : () => <b>Loading...</b>
});

const DynamicSSRFalse = dynamic(() => import("../components/dynamicSSR"), {
  ssr : false,
  loading : () => <b>Loading...</b>
});

export default function Home() {
  const [showDynammic, setShowDynammic] = useState(false);

  const handleClick = () => {
    setShowDynammic(!showDynammic)
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <Link href={{pathname:"/blog"}}><a>Next Link</a></Link>
        
        <br></br>
          <DynamicSSRTrue/> True
        <br></br>
          <DynamicSSRFalse/> False
        <br></br>

        <button className="btn btn-primary" onClick={handleClick}>Show Hide Dynamic Import</button>

        {
           showDynammic && (<HelloComponents/>)
        }
        
      </main>
    </div>
  )
}
